name: GitHub workflow - Java with Gradle

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  job1:
    name: 1. Build jar
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Install JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: .

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: .

      - uses: actions/upload-artifact@v3
        with:
          name: jar_file
          path: ./build/libs


  job2:
    needs: job1
    name: 2. Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: jar_file
          path: ./build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/small-talk:latest
          context: .


  job3:
    needs: job2
    name: 3. Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SMALL_TALK_SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SMALL_TALK_SERVER_PEM_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/small-talk:latest
            sudo docker stop $(sudo docker ps -a -q) || true
            sudo docker system prune -f
            sudo docker run -d -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/small-talk
